version: 0.2

phases:
  build:
    commands:
      - echo "Cleaning old zip"
      - rm -f function.zip
      - echo "Creating fresh zip"
      - zip function.zip lambda_function.py

artifacts:
  files:
    - function.zip
